apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: redis:alpine
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values: 
              - ssd