apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache # Target Deployment Name
  minReplicas: 1       # Minimum number of pods
  maxReplicas: 5       # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU exceeds 50%

# kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10 for creating the hpa 

# for making the load on the pod
# kubectl run -i --tty load-generator --rm --image=busybox:1.28 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done"

