apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: busybox
    env:
    - name: FIRSTNAME
      value: "charan"
    command: [ "sh", "-c", "echo waiting for inti container to start && sleep 3600 "]
  initContainers:
  - name: inti
    image: busybox
    command: ['sh', '-c']
    args: ["until nslookup myservice.default.svc.cluster.local;do echo waiting for the service ;sleep 2 ; done "]