apiVersion: v1
kind: Pod
metadata:
  name: taints
  labels:
    name: myapp
spec:
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"
  containers:
  - name: myapp
    image: redis
